name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby with .ruby-version file
      uses: actions/setup-ruby@v1

    - name: Install Gems
      run: |
        bundle config path vendor/bundle
        bundle config set without 'development'
        bundle install --jobs 4 --retry 3

    - name: Test with Rake
        bundle exec rake
